@StudentsApi_HostAddress = http://localhost:5000

GET {{StudentsApi_HostAddress}}/api/students
Accept: application/json


###

POST {{StudentsApi_HostAddress}}/api/students
Content-Type: application/json

{
  "index": 213456,
  "firstName": "Anna",
  "lastName": "Nowak"
}
