import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-6">
        <div className="flex items-center gap-3">
          <Image src="/fruit.jpg" alt="Fruit" width={100} height={100} />
          <h1 className="mb-4 text-4xl font-bold tracking-tight">Next.js CRUD App</h1>
        </div>
        <hr />
        <p>&nbsp;</p>
        {children}
        Created by Sebastian Wróbel
      </body>
    </html>
  );
}
